### ISSUE TITLE
_jl_call_nogil on macos?

### ISSUE THREAD

**Issue by bjarthur** [cjdoris/PythonCall.jl#693]
the following works fine on linux with python 3.13.2, but not macos with python 3.14.0.  is _jl_call_nogil no supported on macs?

```
Python 3.14.0 | packaged by conda-forge | (main, Oct 12 2025, 19:48:32) [Clang 20.1.8 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from juliacall import Main as jl
>>> jl.Libc.systemsleep(1)
0
>>> jl.Libc.systemsleep._jl_call_nogil(1)
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    jl.Libc.systemsleep._jl_call_nogil(1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arthurb/.julia/packages/PythonCall/wXfah/src/jlwrap/any.jl", line 195, in __getattr__
    return self._jl_callmethod($(pyjl_methodnum(pyjlany_getattr)), k)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Julia: FieldError: type typeof(Base.Libc.systemsleep) has no field `_jl_call_nogil`; typeof(Base.Libc.systemsleep) has no fields at all.
>>> jl.sum([1,1])
2
>>> jl.sum._jl_call_nogil([1,1])
Traceback (most recent call last):
  File "<python-input-4>", line 1, in <module>
    jl.sum._jl_call_nogil([1,1])
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arthurb/.julia/packages/PythonCall/wXfah/src/jlwrap/any.jl", line 195, in __getattr__
    return self._jl_callmethod($(pyjl_methodnum(pyjlany_getattr)), k)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Julia: FieldError: type typeof(sum) has no field `_jl_call_nogil`; typeof(sum) has no fields at all.
>>> jl.VERSION
Julia: v"1.12.0"
```
